#!/bin/bash

#curl "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh" > ~/git-prompt.sh
chmod +x scripts

if ls $HOME/.config/nvim; then
    git -C $HOME/.config/nvim pull
else
    git clone https://github.com/samjtro/nvim $HOME/.config/nvim
fi

cp -r .bashrc .tmux.conf scripts $HOME/
