#!/bin/bash
dt=$(date +%Y%m%d%H%M%S)

if [[ ! -d $HOME/zet/$1 ]]
then
	mkdir $HOME/zet/$1
fi

mkdir $HOME/zet/$1/$2-${dt}
touch $HOME/zet/$1/$2-${dt}/README.md

echo "vi zet/$1/$2-${dt}"
read yn

if [[ yn -ne "n" ]]
then
	vi $HOME/zet/$1/$2-${dt}/README.md
fi
